// lib/stockSymbols.ts - Predefined stock symbols with full company names

export interface StockSymbol {
  symbol: string;
  name: string;
}

export const STOCK_SYMBOLS: StockSymbol[] = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Google)' },
  { symbol: 'META', name: 'Meta Platforms Inc. (Facebook)' },
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc.' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'PG', name: 'Procter & Gamble Co.' },
  { symbol: 'MA', name: 'Mastercard Inc.' },
  { symbol: 'HD', name: 'The Home Depot Inc.' },
  { symbol: 'BAC', name: 'Bank of America Corp.' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'CVX', name: 'Chevron Corporation' },
  { symbol: 'KO', name: 'The Coca-Cola Company' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.' },
  { symbol: 'T', name: 'AT&T Inc.' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'DIS', name: 'The Walt Disney Company' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'CMCSA', name: 'Comcast Corporation' },
  { symbol: 'NFLX', name: 'Netflix Inc.' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'ORCL', name: 'Oracle Corporation' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'NKE', name: 'Nike Inc.' },
  { symbol: 'CRM', name: 'Salesforce Inc.' },
  { symbol: 'MCD', name: "McDonald's Corporation" },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated' },
  { symbol: 'DHR', name: 'Danaher Corporation' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Company' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'ACN', name: 'Accenture plc' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance Inc.' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'UPS', name: 'United Parcel Service Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation' },
  { symbol: 'MO', name: 'Altria Group Inc.' },
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'PM', name: 'Philip Morris International Inc.' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'LOW', name: "Lowe's Companies Inc." },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.' },
  { symbol: 'IBM', name: 'International Business Machines Corporation' },
  { symbol: 'RTX', name: 'RTX Corporation' },
  { symbol: 'NEE', name: 'NextEra Energy Inc.' },
  { symbol: 'BA', name: 'The Boeing Company' },
  { symbol: 'GE', name: 'General Electric Company' },
  { symbol: 'AMT', name: 'American Tower Corporation' },
  { symbol: 'SCHW', name: 'The Charles Schwab Corporation' },
  { symbol: 'SPGI', name: 'S&P Global Inc.' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'BLK', name: 'BlackRock Inc.' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { symbol: 'PLD', name: 'Prologis Inc.' },
  { symbol: 'LRCX', name: 'Lam Research Corporation' },
  { symbol: 'ZTS', name: 'Zoetis Inc.' },
  { symbol: 'TGT', name: 'Target Corporation' },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { symbol: 'MMM', name: '3M Company' },
  { symbol: 'SYK', name: 'Stryker Corporation' },
  { symbol: 'DE', name: 'Deere & Company' },
  { symbol: 'COP', name: 'ConocoPhillips' },
  { symbol: 'NOW', name: 'ServiceNow Inc.' },
  { symbol: 'FIS', name: 'Fidelity National Information Services Inc.' },
  { symbol: 'ADI', name: 'Analog Devices Inc.' },
  { symbol: 'EMR', name: 'Emerson Electric Co.' },
  { symbol: 'SO', name: 'The Southern Company' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'AXP', name: 'American Express Company' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies Inc.' },
  { symbol: 'AIG', name: 'American International Group Inc.' },
  { symbol: 'CB', name: 'Chubb Limited' },
  { symbol: 'EVRG', name: 'Evergy Inc.' },
  { symbol: 'DUK', name: 'Duke Energy Corporation' },
  { symbol: 'PGR', name: 'The Progressive Corporation' },
  { symbol: 'MET', name: 'MetLife Inc.' },
  { symbol: 'PRU', name: 'Prudential Financial Inc.' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation' },
  { symbol: 'ITW', name: 'Illinois Tool Works Inc.' },
  { symbol: 'KMB', name: 'Kimberly-Clark Corporation' },
  { symbol: 'CL', name: 'Colgate-Palmolive Company' },
  { symbol: 'MKC', name: 'McCormick & Company Incorporated' },
  { symbol: 'HSY', name: 'The Hershey Company' },
  { symbol: 'TAP', name: 'Molson Coors Beverage Company' },
  { symbol: 'KR', name: 'The Kroger Co.' },
  { symbol: 'ADM', name: 'Archer-Daniels-Midland Company' },
  { symbol: 'GIS', name: 'General Mills Inc.' },
  { symbol: 'FDX', name: 'FedEx Corporation' },
  { symbol: 'CSX', name: 'CSX Corporation' },
  { symbol: 'KHC', name: 'The Kraft Heinz Company' },
  { symbol: 'EW', name: 'Edwards Lifesciences Corporation' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corporation' },
  { symbol: 'BAX', name: 'Baxter International Inc.' },
  { symbol: 'SPG', name: 'Simon Property Group Inc.' },
  { symbol: 'PLNT', name: 'Planet Fitness Inc.' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp' },
  { symbol: 'KEY', name: 'KeyCorp' },
  { symbol: 'RF', name: 'Regions Financial Corporation' },
  { symbol: 'STI', name: 'SunTrust Banks Inc.' },
  { symbol: 'USB', name: 'U.S. Bancorp' },
  { symbol: 'HBAN', name: 'Huntington Bancshares Incorporated' },
  { symbol: 'CFG', name: 'Citizens Financial Group Inc.' },
  { symbol: 'MTB', name: 'M&T Bank Corporation' },
  { symbol: 'ZION', name: 'Zions Bancorporation N.A.' },
  { symbol: 'PNC', name: 'The PNC Financial Services Group Inc.' },
  { symbol: 'COF', name: 'Capital One Financial Corporation' },
  { symbol: 'SYF', name: 'Synchrony Financial' },
  { symbol: 'AON', name: 'Aon plc' },
  { symbol: 'AIZ', name: 'Assurant Inc.' },
  { symbol: 'AFL', name: 'Aflac Incorporated' },
  { symbol: 'WRB', name: 'W.R. Berkley Corporation' },
  { symbol: 'XLNX', name: 'Xilinx Inc.' },
  { symbol: 'QRVO', name: 'Qorvo Inc.' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.' },
  { symbol: 'ETSY', name: 'Etsy Inc.' },
  { symbol: 'EBAY', name: 'eBay Inc.' },
  { symbol: 'ROST', name: 'Ross Stores Inc.' },
  { symbol: 'TJX', name: 'The TJX Companies Inc.' },
  { symbol: 'SKX', name: 'Skechers U.S.A. Inc.' },
  { symbol: 'GPS', name: 'The Gap Inc.' },
  { symbol: 'NOC', name: 'Northrop Grumman Corporation' },
  { symbol: 'TEL', name: 'TE Connectivity Ltd.' },
  { symbol: 'CTAS', name: 'Cintas Corporation' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'ANSS', name: 'ANSYS Inc.' },
  { symbol: 'MDB', name: 'MongoDB Inc.' },
  { symbol: 'SNPS', name: 'Synopsys Inc.' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.' },
  { symbol: 'WDC', name: 'Western Digital Corporation' },
  { symbol: 'MU', name: 'Micron Technology Inc.' },
  { symbol: 'TT', name: 'Trane Technologies plc' },
  { symbol: 'APH', name: 'Amphenol Corporation' },
  { symbol: 'MCHP', name: 'Microchip Technology Incorporated' },
  { symbol: 'MRNA', name: 'Moderna Inc.' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.' },
  { symbol: 'BIIB', name: 'Biogen Inc.' },
  { symbol: 'ALGN', name: 'Align Technology Inc.' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.' },
  { symbol: 'NET', name: 'Cloudflare Inc.' },
  { symbol: 'ZM', name: 'Zoom Video Communications Inc.' },
  { symbol: 'DOCU', name: 'DocuSign Inc.' },
  { symbol: 'OKTA', name: 'Okta Inc.' },
  { symbol: 'ZS', name: 'Zscaler Inc.' },
  { symbol: 'SPLK', name: 'Splunk Inc.' },
  { symbol: 'DDOG', name: 'Datadog Inc.' },
  { symbol: 'ESTC', name: 'Elastic N.V.' },
  { symbol: 'PSTG', name: 'Pure Storage Inc.' },
  { symbol: 'DT', name: 'Dynatrace Inc.' },
  { symbol: 'HUBS', name: 'HubSpot Inc.' },
  { symbol: 'TEAM', name: 'Atlassian Corporation' },
  { symbol: 'SHOP', name: 'Shopify Inc.' },
  { symbol: 'SQ', name: 'Block Inc. (Square)' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc.' },
  { symbol: 'AKAM', name: 'Akamai Technologies Inc.' },
  { symbol: 'MTCH', name: 'Match Group Inc.' },
  { symbol: 'TWLO', name: 'Twilio Inc.' },
  { symbol: 'ZBRA', name: 'Zebra Technologies Corporation' },
  { symbol: 'ANET', name: 'Arista Networks Inc.' },
  { symbol: 'NTAP', name: 'NetApp Inc.' },
  { symbol: 'WLTW', name: 'Willis Towers Watson Public Limited Company' },
  { symbol: 'AAL', name: 'American Airlines Group Inc.' },
  { symbol: 'DAL', name: 'Delta Air Lines Inc.' },
  { symbol: 'UAL', name: 'United Airlines Holdings Inc.' },
  { symbol: 'LUV', name: 'Southwest Airlines Co.' },
  { symbol: 'CCL', name: 'Carnival Corporation & plc' },
  { symbol: 'MAR', name: 'Marriott International Inc.' },
  { symbol: 'HLT', name: 'Hilton Worldwide Holdings Inc.' },
  { symbol: 'WYNN', name: 'Wynn Resorts Limited' },
  { symbol: 'MGM', name: 'MGM Resorts International' },
  { symbol: 'LVS', name: 'Las Vegas Sands Corp.' },
  { symbol: 'RCL', name: 'Royal Caribbean Cruises Ltd.' },
  { symbol: 'DHI', name: 'D.R. Horton Inc.' },
  { symbol: 'LEN', name: 'Lennar Corporation' },
  { symbol: 'NVR', name: 'NVR Inc.' },
  { symbol: 'KBH', name: 'KB Home' },
  { symbol: 'PHM', name: 'PulteGroup Inc.' },
  { symbol: 'LHX', name: 'L3Harris Technologies Inc.' },
  { symbol: 'HRS', name: 'Harris Corporation' },
  { symbol: 'ROP', name: 'Roper Technologies Inc.' },
  { symbol: 'CMI', name: 'Cummins Inc.' },
  { symbol: 'PNR', name: 'Pentair plc' },
  { symbol: 'IR', name: 'Ingersoll Rand Inc.' },
  { symbol: 'KSU', name: 'Kansas City Southern' },
  { symbol: 'NSC', name: 'Norfolk Southern Corporation' },
  { symbol: 'UNP', name: 'Union Pacific Corporation' },
  { symbol: 'CP', name: 'Canadian Pacific Railway Limited' },
  { symbol: 'HPQ', name: 'HP Inc.' },
  { symbol: 'SYY', name: 'Sysco Corporation' },
  { symbol: 'CAH', name: 'Cardinal Health Inc.' },
  { symbol: 'BDX', name: 'Becton Dickinson and Company' },
  { symbol: 'FTNT', name: 'Fortinet Inc.' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.' },
  { symbol: 'CHTR', name: 'Charter Communications Inc.' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill Inc.' },
  { symbol: 'HCA', name: 'HCA Healthcare Inc.' },
  { symbol: 'LH', name: 'Laboratory Corporation of America Holdings' },
  { symbol: 'HOLX', name: 'Hologic Inc.' },
  { symbol: 'ZBH', name: 'Zimmer Biomet Holdings Inc.' },
  { symbol: 'ABMD', name: 'Abiomed Inc.' },
  { symbol: 'XRAY', name: 'Dentsply Sirona Inc.' },
  { symbol: 'AAP', name: 'Advance Auto Parts Inc.' },
  { symbol: 'ORLY', name: "O'Reilly Automotive Inc." },
  { symbol: 'AZO', name: 'AutoZone Inc.' },
  { symbol: 'GPC', name: 'Genuine Parts Company' },
  { symbol: 'TSCO', name: 'Tractor Supply Company' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.' },
  { symbol: 'EQIX', name: 'Equinix Inc.' },
  { symbol: 'PSA', name: 'Public Storage' },
  { symbol: 'AME', name: 'AMETEK Inc.' },
  { symbol: 'EMN', name: 'Eastman Chemical Company' },
  { symbol: 'AXTA', name: 'Axalta Coating Systems Ltd.' },
  { symbol: 'WRK', name: 'WestRock Company' },
  { symbol: 'PPG', name: 'PPG Industries Inc.' },
  { symbol: 'SHW', name: 'The Sherwin-Williams Company' },
  { symbol: 'MLM', name: 'Martin Marietta Materials Inc.' },
  { symbol: 'AVY', name: 'Avery Dennison Corporation' },
  { symbol: 'ECL', name: 'Ecolab Inc.' },
  { symbol: 'FMC', name: 'FMC Corporation' },
  { symbol: 'CF', name: 'CF Industries Holdings Inc.' },
  { symbol: 'BKR', name: 'Baker Hughes Company' },
  { symbol: 'HAL', name: 'Halliburton Company' },
  { symbol: 'SLB', name: 'Schlumberger Limited' },
  { symbol: 'NOV', name: 'National Oilwell Varco Inc.' },
  { symbol: 'WMB', name: 'The Williams Companies Inc.' },
  { symbol: 'KMI', name: 'Kinder Morgan Inc.' },
  { symbol: 'EPD', name: 'Enterprise Products Partners L.P.' },
  { symbol: 'ET', name: 'Energy Transfer LP' },
  { symbol: 'KSS', name: "Kohl's Corporation" },
  { symbol: 'JWN', name: 'Nordstrom Inc.' },
  { symbol: 'ANF', name: 'Abercrombie & Fitch Co.' },
  { symbol: 'DKNG', name: 'DraftKings Inc.' },
  { symbol: 'PENN', name: 'Penn National Gaming Inc.' },
  { symbol: 'CZR', name: 'Caesars Entertainment Inc.' },
  { symbol: 'BYND', name: 'Beyond Meat Inc.' },
  { symbol: 'SFM', name: 'Sprouts Farmers Market Inc.' },
  { symbol: 'SMPL', name: 'The Simply Good Foods Company' },
  { symbol: 'CAG', name: 'Conagra Brands Inc.' },
  { symbol: 'CLX', name: 'The Clorox Company' },
  { symbol: 'K', name: 'Kellogg Company' },
  { symbol: 'DPS', name: 'Dr Pepper Snapple Group Inc.' },
  { symbol: 'PFG', name: 'Principal Financial Group Inc.' },
  { symbol: 'L', name: 'Loews Corporation' },
  { symbol: 'BHF', name: 'Brighthouse Financial Inc.' },
  { symbol: 'BXP', name: 'Boston Properties Inc.' },
  { symbol: 'VNO', name: 'Vornado Realty Trust' },
  { symbol: 'SLG', name: 'SL Green Realty Corp.' },
  { symbol: 'FRT', name: 'Federal Realty Investment Trust' },
  { symbol: 'EQR', name: 'Equity Residential' },
  { symbol: 'AVB', name: 'AvalonBay Communities Inc.' },
  { symbol: 'ESS', name: 'Essex Property Trust Inc.' },
];

// Convert to Listing format for compatibility
export function getStockListings(): Array<{ symbol: string; name: string; exchange: string }> {
  return STOCK_SYMBOLS.map(stock => ({
    symbol: stock.symbol,
    name: stock.name,
    exchange: 'NASDAQ' // Default exchange, can be enhanced later
  }));
}


